apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-configmap
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  {{- range $key, $val := .Values.noteBookStorage }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  {{- range $key, $val := .Values.sparkEventLog }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zeppelin-configmap
data:
{{ (.Files.Glob "zeppelinConf/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-spark-configmap
data:
{{ (.Files.Glob "sparkConf/*").AsConfig | indent 2 }}
---
{{- if .Values.mountSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{- end }}