apiVersion: v1
kind: Service
metadata:
  name: {{ template "jupyter-with-spark.fullname" . }}
  labels:
    app: {{ template "jupyter-with-spark.name" . }}
    chart: {{ template "jupyter-with-spark.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.jupyterService.type | default "LoadBalancer" | quote }}
  ports:
    - port: {{ .Values.jupyterService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "jupyter-with-spark.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jupyter-with-spark.fullname" . }}-spark-web-ui
  labels:
    app: {{ template "jupyter-with-spark.name" . }}
    chart: {{ template "jupyter-with-spark.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.sparkWebUI.type | default "LoadBalancer" | quote }}
  ports:
    - port: {{ .Values.sparkWebUI.port }}
      targetPort: web-ui
      protocol: TCP
      name: web-ui
  selector:
    app: {{ template "jupyter-with-spark.name" . }}
    release: {{ .Release.Name }}