# Default values for snappydata.
# This is a YAML-formatted file.

image: snappydatainc/snappydata
imageTag: 1.0.2.1
imagePullPolicy: IfNotPresent

locators:
  ## config options for locators
  conf: ""
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    requests:
    #  cpu: 100m
      memory: 1024Mi
  ## PV configuration
  persistence:
    ## Use 'storageClass' to specify the storageClassName to be used while dynamically provisioning volumes
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, Azure & OpenStack)
    ##
    # storageClass:
    accessMode: ReadWriteOnce
    size: 10Gi

servers:
  replicaCount: 2
  ## config options for servers
  conf: "-heap-size=5g"
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    requests:
    #  cpu: 100m
      memory: 6144Mi
  ## PV configuration
  persistence:
    ## Use 'storageClass' to specify the storageClassName to be used while dynamically provisioning volumes
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, Azure & OpenStack)
    ##
    # storageClass:
    accessMode: ReadWriteOnce
    size: 10Gi

leaders:
  ## config options for leaders
  conf: "-heap-size=5g -zeppelin.interpreter.enable=true -snappydata.hiveServer.enabled=true"
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    requests:
    #  cpu: 100m
      memory: 6144Mi
  ## PV configuration
  persistence:
    ## Use 'storageClass' to specify the storageClassName to be used while dynamically provisioning volumes
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, Azure & OpenStack)
    ##
    # storageClass:
    accessMode: ReadWriteOnce
    size: 10Gi

nodeSelector: {}

tolerations: []

affinity: {}
