apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-configmap
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.historyServerConf }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- if .Values.mountSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{- end }}